export const STOCK_REQUEST_SELECT = `
  id,
  company_id,
  business_unit_id,
  fulfilling_business_unit_id,
  request_code,
  request_date,
  required_date,
  department,
  status,
  priority,
  purpose,
  notes,
  requested_by_user_id,
  requested_by_name,
  approved_by,
  approved_at,
  picked_by,
  picked_at,
  received_by,
  received_at,
  created_at,
  created_by,
  updated_at,
  updated_by,
  deleted_at,
  version,
  requesting_business_unit:business_units!stock_requests_business_unit_id_fkey(
    id,
    code,
    name
  ),
  fulfilling_business_unit:business_units!stock_requests_fulfilling_business_unit_id_fkey(
    id,
    code,
    name
  ),
  requested_by_user:users!stock_requests_requested_by_user_id_fkey(
    id,
    email,
    first_name,
    last_name
  ),
  received_by_user:users!stock_requests_received_by_fkey(
    id,
    email,
    first_name,
    last_name
  ),
  stock_request_items(
    id,
    stock_request_id,
    item_id,
    requested_qty,
    picked_qty,
    dispatch_qty,
    item_unit_option_id,
    selected_item_batch_id,
    uom_id,
    notes,
    created_at,
    updated_at,
    items(
      id,
      item_code,
      item_name,
      uom_id,
      base_unit:units_of_measure!items_uom_id_fkey(
        id,
        code,
        name,
        symbol
      )
    ),
    units_of_measure(id, code, symbol),
    selected_item_batch:item_batches!stock_request_items_selected_item_batch_id_fkey(
      id,
      batch_code,
      received_at,
      warehouse:warehouses!item_batches_warehouse_id_fkey(
        id,
        warehouse_code,
        warehouse_name
      )
    ),
    item_unit_options(
      id,
      item_id,
      uom_id,
      option_label,
      qty_per_unit,
      barcode,
      is_base,
      is_default,
      is_active,
      sort_order,
      units_of_measure(
        id,
        code,
        name,
        symbol
      )
    )
  ),
  delivery_note_sources(
    created_at,
    delivery_notes!delivery_note_sources_dn_id_fkey(
      id,
      dn_no,
      status,
      created_at
    )
  )
`;
