-- Ensure delivery note numbers are generated by exactly one trigger.
-- Older migrations created trigger_generate_delivery_note_number, while the
-- 9-digit generator migration created trigger_generate_delivery_note_no. If
-- both exist, the first trigger fills dn_no and the second rejects the row as
-- app-supplied input.

DROP TRIGGER IF EXISTS trigger_generate_delivery_note_number ON public.delivery_notes;
DROP TRIGGER IF EXISTS trigger_generate_delivery_note_no ON public.delivery_notes;

CREATE TRIGGER trigger_generate_delivery_note_no
  BEFORE INSERT ON public.delivery_notes
  FOR EACH ROW
  EXECUTE FUNCTION public.apply_generated_document_code('dn_no', 'DN', '9');
